### ISSUE TITLE
Error with BookshelfAdapter

### ISSUE THREAD

**Issue by schtibe** [endpoints/endpoints#140]
According to the documentation, a controller is written like this (the example does it a little different)
    // src/modules/authors/controller.js
    const Endpoints = require('endpoints');
 
    module.exports = new Endpoints.Controller({
      adapter: new Endpoints.BookshelfAdapter({
        model: require('./model')
      })
    });

If I do it like this, I get roughly the following error:

    /usr/src/app/backend/node_modules/endpoints/es5/application/lib/require_search.js:32
        throw result;
              ^
    TypeError: undefined is not a function
        at Object.<anonymous> (/usr/src/app/backend/src/modules/users/controller.js:3:15)
        at Module._compile (module.js:431:26)

When I grep for BookshelfAdapter in the endpoints source code, I can't even find anything like this, except for documentation files. Is the documentation outdated?

**Comment by ashleygwilliams** [comment]
hi! @schtibe the documentation is out of date. this is now called store-bookshelf https://github.com/endpoints/endpoints/tree/master/src/store-bookshelf

the example is up to date, and when i get a free moment i will update the documentation. feel free to jump in #endpoints on irc if you need help- or email me (address in profile) 

sorry about this and thanks for filiing an issue!

**Comment by ashleygwilliams** [comment]
the controller code should basically look like this:

```
const thisFolderName = __dirname.split('/').pop();

const API = require('../../classes/api');

module.exports = new API.Controller({
  model: require('./model'),
  basePath: thisFolderName
});
```

**Comment by schtibe** [comment]
Ok, yes I'm using it this way.
What I yet don't understand is where to put the method for `controller.create`, that is, the documented `opts.method` in http://endpointsjs.com/guides/controller-module.

**Comment by teckays** [comment]
... looks like this project is dead!
